---
title: "BOUKHALFA"
author: "Mélina Boukhalfa"
format: html
---
#Introduction
## Study organisation
###  Question 1 

```{r}
library(here)
library(vroom)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(knitr)
```

```{r}
here::i_am("grades-lab.Rproj")
```

```{r}
course_description<-vroom(here("data","courses.csv"))
```

### Question 2
```{r}
course_description|>
  rename("identifier"=course_id,
         "number of exams"=nb_grades)|>
  arrange(course) |>knitr::kable()
```
## Students 
### Question 3

```{r}
students<-vroom(here("data","students.csv"), col_types = cols(
                       birth_date=col_date()))
```
The birth

## Grades 
### Question 4

```{r}
grades<-read.csv(here("data","grades.csv"))
grades<-read.csv("data/grades.csv", na.strings = "_")
grades<-vroom(here("data","grades.csv"),delim=":")
```

# Student population analysis
## Question 5 

```{r}
ggplot(students,aes(x=factor(group))) +
         geom_bar(position = "dodge")+
         theme_bw()
```
## Question 6
```{r}
ggplot(students,aes(x=factor(group), fill=sex)) +
         geom_bar(position="fill")+
         theme_bw()
```

## Question 7 
```{r}
age_students <- students|>
  mutate(
    age = as.numeric(format(Sys.Date(), "%Y")) - as.numeric(format(birth_date, "%Y")))
```

```{r}
ggplot(age_students,aes(x=age))+
  geom_density(bw="sj")+theme_minimal()
```

## Question 8 
```{r}
age_students|>group_by(group)|>summarise(median=median(age))|>
  knitr::kable()
```

## Question 9 

```{r}
age_students|> group_by(group)|>
  slice_max(age)|> 
  arrange(desc(age))|>
  summarise(identifier=id, sex=sex,age=age)|>
  knitr::kable()
```
# Simple grade analysis
## Question 10 

The data set contains `r sum(!is.na(course_description$nb_grades))` grades.

